domain: danielofodile.github.io
url: https://danielofodile.github.io
baseurl: /E-commerce_website/
theme: jekyll-theme-minimal
title: E-commerce Website
description: A virtual market place that allows users buy and sell goods and digital products with ease.
lsi: false
safe: true
source: main
incremental: false
highlighter: rouge
gist:
  noscript: false
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge
nav:
  - Home: /index.html
  - About: /about.html
  - Blog: /blog.html
  - Contact: /contact.html
  - Authors: /authors.html
  - Features: /features.html

plugins:
  - jekyll-collections
